name: Crear recomendación en GitHub Issue

on:
  workflow_dispatch:

jobs:
  crear-recomendacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Instalar dependencias
        run: npm install octokit
      - name: Ejecutar script para crear issue
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/actions-scripts/use-the-api.mjs
